### PR TITLE
build openmp libraries

### PR DESCRIPTION
**Pull request by kalmarek**
things run here and past tests; 
but let someone with more experience with C have a look;

I noticed that multi-threading is disabled if I start julia in parallel, like `julia -p4`
(Guess this is to disable over-threading i.e. multiple processes run multiple threads).

### CODE REVIEW

**Comment by mlubin** [comment]
CC @tkelman

**Comment by mlubin** [comment]
Please add a discussion in the README about how to control SCS's use of threads.

**Comment by tkelman** [comment]
do all mac source toolchains have working openmp by now?

**Comment by kalmarek** [comment]
I can't find a reference why the openmp threading is disabled when called from worker;
also https://github.com/JuliaLang/julia/issues/6293 suggests that the number should not exceed the number of _physical cores_ in processor

**Comment by mlubin** [comment]
@kalmarek, have you tested this with both openblas and mkl?

**Comment by kalmarek** [comment]
I did, but to avoid a repetition, let me do it again on a fresh install (tonight or tomorrow)

**Comment by kalmarek** [comment]
this has been tested with both openblas and mkl;
Both openblas- and mkl-linked `libscsdir.so` are able to use up to `$physical_cores`-threads

**Comment by kalmarek** [comment]
I think we can scrap this pull: surprisingly the library is as multithreaded as BLAS is, regardless of linking;

Maybe the part about interaction of `addprocs` and `BLAS.set_num_threads()` in README is worth keeping.

**Comment by kalmarek** [comment]
After the discussion https://github.com/cvxgrp/scs/issues/81 I think I finally got it right;

Linking to openmp is relevant only for Lin-sys phase of the solver, and only if the indirect solver is used;
(this makes linking of `SCSdir` with `-lgomp` superfluous, but the code is much simpler).

**Pull request closed without merging**
