### PR TITLE
efficiency improvements for MPB wrapper

### PR DESCRIPTION
**Pull request by mlubin**
I was trying to load a problem with >100,000 separate linear cones and 6,000 second-order cones, and the current wrapper wasn't cutting it. This version is *much* faster.

### CODE REVIEW

**Comment by tkelman** [comment]
CSC FTW. Trouble on nightly though? Odd, been okay on PkgEvaluator?

**Comment by mlubin** [comment]
I hadn't tested locally on 0.4, will look into it.

**Comment by mlubin** [comment]
Tests are passing locally on 0.4, so not sure what's going on there.

**Comment by mlubin** [comment]
Also, the failure is in the direct interface which this PR doesn't touch.

**Comment by bodono** [comment]
Can this be merged?

**Comment by mlubin** [comment]
I'll rebase to see if travis passes.

**Comment by madeleineudell** [comment]
And for peace of mind, all the Convex.jl tests pass with this commit
rebased on master.

On Thu, Jun 18, 2015 at 2:14 PM, Miles Lubin <notifications@github.com>
wrote:

> I'll rebase to see if travis passes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/SCS.jl/pull/25#issuecomment-113291814>.
>



-- 
Madeleine Udell
www.stanford.edu/~udell

**Comment by mlubin** [comment]
Same failure on 0.4 linux:
```
ERROR: LoadError: LoadError: OverflowError()
 in hcat at abstractarray.jl:641
 in feasible_exponential_conic at /home/travis/.julia/v0.4/SCS/test/direct.jl:73
```
No clue here, as I mentioned above this is in a part of the code which the PR doesn't touch.

**Comment by bodono** [comment]
Yeah, that's a bug in julia. I change the test to get around the bug here: https://github.com/JuliaOpt/SCS.jl/pull/28, but that test fails from another bug in julia.

**Comment by mlubin** [comment]
This is passing on linux now.

**Pull request merged**
