### PR TITLE
Use v1.1.5 and update windows binary checksums accordingly

### PR DESCRIPTION
**Pull request by tkelman**
note - not tested locally yet, just built and uploaded so far

### CODE REVIEW

**Comment by bodono** [comment]
Ship it!

**Comment by mlubin** [comment]
Will people who already have SCS installed get updated to the new binaries with ``Pkg.update()``? It looks like they won't?

**Comment by tkelman** [comment]
No, I don't think that will happen automatically. Even `Pkg.build` might not force a re-download / re-build I think, unless maybe there's a validation routine that we can use to distinguish between the two versions of the library?

**Comment by mlubin** [comment]
@bodono, does SCS export a function to ask for the compiled version?

**Comment by tkelman** [comment]
I do see an `scs_version` exported from the dll

**Comment by bodono** [comment]
Right, there's a c function `scs_version` that returns a string, e.g. "1.1.5" right now, but it's not being exposed though SCS.jl right now. Should I add it?

**Comment by bodono** [comment]
PR here: https://github.com/JuliaOpt/SCS.jl/pull/33

**Pull request merged**
