### PR TITLE
add power cone interface and power cone test

### PR DESCRIPTION
**Pull request by bodono**
This is the last part of the transition to the new SCS API, this is simply adding the power cone capability and a new test.

Note that the MathProgBase tests start failing randomly with this change, but I'm pretty sure the root cause is not this change but actually this issue: https://github.com/JuliaOpt/SCS.jl/issues/31.

### CODE REVIEW

**Comment by mlubin** [comment]
On 0.4, there's a real error here:
```
ERROR: LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Ptr{Float64}}, ::Array{Float64,1})
This may have arisen from a call to the constructor Ptr{Float64}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{Ptr{T}}, !Matched::UInt64)
  convert{T}(::Type{Ptr{T}}, !Matched::Int64)
```

**Comment by bodono** [comment]
Confirmed this fixes https://github.com/JuliaOpt/SCS.jl/issues/31. It passes all the same tests as master (and fails the same one, which I think should be resolved by https://github.com/staticfloat/homebrew-juliadeps/pull/56/files), so should be safe to merge.

**Comment by madeleineudell** [comment]
This is only failing on the nightly Mac build, passing on all others. I'm going to merge.

**Comment by madeleineudell** [comment]
closes #31

**Pull request merged**
