### PR TITLE
Implement getconicdual

### PR DESCRIPTION
**Pull request by karanveerm**
They are passing the MPB tests except the SDP test where duals don't work. That should be fixed once we move on to the newer symmetric SDP format. The sign flipping remains unclear.

### CODE REVIEW

**Comment by karanveerm** [comment]
@mlubin @madeleineudell @jennyhong Does anyone have any concerns or can I go ahead, merge this in and release SCS.jl v0.0.1?

**Comment by jennyhong** [comment]
:+1:

**Comment by mlubin** [comment]
JuMP has some additional tests for duals. Let me test this out tonight before merging.

**Comment by karanveerm** [comment]
Sorry, I forgot to test with JuMP and had a bug in :NonPos (which is not used with Convex). Please pull my latest commit.

**Comment by mlubin** [comment]
Thanks for testing with JuMP, looks good to me now.

**Pull request merged**
