### PR TITLE
Add symmetry constraints for SCS

### LINKED ISSUE #8: Add symmetry constraints for SDP
The MPB interface implicitly assumes that SDP constraints imply symmetry, but SCS needs these as explicit equalities, see discussion here: https://github.com/JuliaOpt/Mosek.jl/issues/29#issuecomment-66731064. These equalities should be introduced in SCS.jl and not by Convex.jl.

### PR DESCRIPTION
**Pull request by karanveerm**
All Convex.jl tests also continue to pass. Fixes #8. Can be made more efficient.

### CODE REVIEW

**Comment by karanveerm** [comment]
The tests are passing on Windows, but not on OSX or Linux.
```
/home/travis/julia/bin/julia: symbol lookup error: /home/travis/.julia/v0.3/SCS/deps/usr/lib/libscsdir.so: undefined symbol: dsyevr_64_
```
dysevr seems to be an LAPACK function (http://phase.hpcc.jp/mirrors/netlib/lapack/double/dsyevr.f)

@mlubin Any ideas? Turns out the only previous SDP test is also commented out https://github.com/JuliaOpt/SCS.jl/blob/master/test/direct.jl#L117 and only SDPs use BLAS/LAPACK.

**Comment by mlubin** [comment]
Oh, that's an unfortunate hole in the test coverage! I'll take a look.

**Comment by mlubin** [comment]
I reset travis and it seems okay now.

**Comment by joehuchette** [comment]
In keeping with the [MPB conic interface](http://mathprogbasejl.readthedocs.org/en/latest/conic.html), shouldn't this be handled at at the Convex.jl level instead?

**Comment by mlubin** [comment]
I don't think SCS implements the new lower triangle SDP format yet... this should change.

**Comment by bodono** [comment]
SCS has supported the lower triangle SDP format for a while, since this commit 9188912c7eb0bf80b796fbef6ce8235ae2437d25. I don't think the bundled up SCS packages contain that change yet though.

**Comment by mlubin** [comment]
@bodono, ah yes, I mean the wrapper. Is the lower triangle SDP format on the master branch of SCS now?

**Comment by bodono** [comment]
Yep, the master branch of the core SCS project uses the lower triangular SDP format.

**Pull request merged**
