### PR TITLE
support blas-reference

### PR DESCRIPTION
**Pull request by kalmarek**
for those brave to build julia on their own

### CODE REVIEW

**Comment by mlubin** [comment]
Could you add a comment describing in what situations `blasvendor == :unknown` can occur?

**Comment by kalmarek** [comment]
e.g. when julia is compiled with `blas-reference`. This may happen e.g. in certain gentoo Linux configurations

**Comment by mlubin** [comment]
I meant a comment in the code :)

**Comment by kalmarek** [comment]
ok, so it turns out that it is not that simple (i.e. we could scrap this pull)

julia comes with its own (internal) BLAS library, and since we don't link `libscs*` with any blas/lapack, the library uses those symbols which are loaded with julia, i.e. julia's BLAS. Now if julia is to run on a hardened system (this was the actual cause fo problems) linking must be immediate, hence the needed `-lblas -llapack`. However then we link against whatever system provides we risk using two BLASes at the same time.

A solution would be to find out the exact path of BLAS julia uses (internal, or systems) and link against it, but I have no idea how to do it.

**Comment by mlubin** [comment]
I would recommend looking at BinaryBuilder before putting too much more effort into this build script (ideally the BinaryBuilder version will replace this). BinaryBuilder is designed to link against the libraries that ship with Julia (including gfortran and BLAS). I don't know, however, what this means for MKL builds.

**Comment by kalmarek** [comment]
BinaryBuilder was more pleasant than expected:

https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/313

There is a problem with building for windows with openmp enabled. Everything else works fine.

At least in the wizard ;-)

**Comment by mlubin** [comment]
Glad to hear that you got it almost working :)

Yes, there are lots of trade-offs with BinaryBuilder. We should ensure that users still have an option to build from source, and it's also not necessary to immediately get rid of the BinDeps script for linux (we still use it for Ipopt, for example). But for MacOS and Windows binaries I don't know of any other practical way that we can move forward and get something workable enough to tag a new release.

**Pull request closed without merging**
