### PR TITLE
update status_mapt to latest constants

### PR DESCRIPTION
**Pull request by kalmarek**
Does `SCS_SOLVED_INACCURATE` qualify for `:UserLimit`?

### CODE REVIEW

**Comment by mlubin** [comment]
What are the conditions that could trigger that status? If it's an iteration limit, then yes, I'd say ``UserLimit``.

By the way, we're thinking about reworking the MathProgBase status system because it's pretty broken at the moment, see the discussion at https://github.com/JuliaOpt/MathProgBase.jl/issues/156.

**Comment by kalmarek** [comment]
Yest this can be an iteration limit

**Comment by mlubin** [comment]
``UserLimit`` isn't appropriate if the solver stops because of an iteration limit which the user didn't set.

**Comment by kalmarek** [comment]
I'm pretty sure this is me being dumb, but I have no idea how to distinguish `SCSSolver()` and `SCSSolver(iterations=20000)` in code; for the first hitting its default 20000 iterations shouldn't return `:UserLimit`, while the second should not (then what should it return? `:Inaccurate`?)

How is discussion on extending the number of solve states progressing?

**Comment by mlubin** [comment]
User-provided options are stored in ``SCSMathProgModel.options``, so you can check if ``max_iters`` was set. If SCS stops because it hit the user-provided iteration limit, it should return ``:UserLimit``. If it stops because it hits its internal limit without solving the problem, it should return something like ``:Error``.

I wouldn't expect a revision of the MPB solver statuses until June.

**Pull request closed without merging**
