### PR TITLE
Fix start value

### PR DESCRIPTION
**Pull request by blegat**
Closes https://github.com/JuliaOpt/SCS.jl/issues/136

### CODE REVIEW

**Comment by kalmarek** [comment]
maybe I'm using it wrong but here is what I tried:
```julia
function example_problem(m = Model())
    @variable(m, x >= 0)
    @variable(m, y <= 2)
    @variable(m, P[1:2,1:2] >= 0)
    @objective(m, Max, x+y + P[1,1] - P[2,2])
    @constraint(m, x <= y+4)
    @constraint(m, P[1,1] + P[2,2] <= 4)
    @constraint(m, P[2,1] - P[1,1] <= 4)
    
    return m
end

m = example_problem()
optimize!(m, with_optimizer(SCS.Optimizer, eps=1e-10))

solvedx = value(m[:x])
solvedy = value(m[:y])
solvedP = value.(m[:P])

m2 = example_problem()
set_start_value(m2[:x], solvedx)
set_start_value(m2[:y], solvedy)
set_start_value.(m2[:P], solvedP)

optimize!(m2, with_optimizer(SCS.Optimizer, eps=1e-10, max_iters=3, warm_start=true))
@assert termination_status(m2) == termination_status(m) # fails
```

I can however overwrite SCS.MOISolution:
```julia
primal = backend(m).optimizer.model.optimizer.sol.primal
dual = backend(m).optimizer.model.optimizer.sol.dual
slack = backend(m).optimizer.model.optimizer.sol.slack

m3 = example_problem(Model(with_optimizer(SCS.Optimizer, eps=1e-10, max_iters=3, warm_start=true)))

m3.moi_backend.optimizer.model.optimizer.sol.primal = primal
m3.moi_backend.optimizer.model.optimizer.sol.dual = dual
m3.moi_backend.optimizer.model.optimizer.sol.slack = slack

optimize!(m3)
@assert termination_status(m3) == termination_status(m) # this works
```

**Comment by blegat** [comment]
What is the termination status for `m2` ?

**Comment by kalmarek** [comment]
```julia
m2 = example_problem()
set_start_value(m2[:x], solvedx)
set_start_value(m2[:y], solvedy)
set_start_value.(m2[:P], solvedP)

with_SCS_3iters = with_optimizer(SCS.Optimizer, eps=1e-10, max_iters=3, warm_start=true)
optimize!(m2, with_SCS_3iters)
termination_status(m2)
```
```
----------------------------------------------------------------------------
	SCS v2.0.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2017
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 12, CG tol ~ 1/iter^(2.00)
eps = 1.00e-10, alpha = 1.50, max_iters = 3, normalize = 1, scale = 1.00
acceleration_lookback = 20, rho_x = 1.00e-03
Variables n = 6, constraints m = 9
Cones:	linear vars: 9
Setup time: 3.03e-05s
SCS using variable warm-starting
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 8.03e+00  1.75e+00  7.88e-01 -7.37e+01 -8.29e+00  0.00e+00  1.89e-05 
     3| 7.00e-01  5.44e-01  9.19e-01  2.76e+00 -8.51e+00  8.83e-16  3.28e-05 
----------------------------------------------------------------------------
Status: Solved/Inaccurate
Hit max_iters, solution may be inaccurate
Timing: Solve time: 3.39e-05s
	Lin-sys: avg # CG iterations: 2.50, avg solve time: 9.99e-07s
	Cones: avg projection time: 1.84e-07s
	Acceleration: avg step time: 1.94e-06s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 7.6374e-01, dist(y, K*) = 0.0000e+00, s'y/|s||y| = -1.3466e-01
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 6.9958e-01
dual res:   |A'y + c|_2 / (1 + |c|_2) = 5.4372e-01
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 9.1850e-01
----------------------------------------------------------------------------
c'x = 2.7591, -b'y = -8.5115
============================================================================

ALMOST_OPTIMAL::TerminationStatusCode = 7
```
compare with the same problem where start values are not set:
```julia
m2 = example_problem()
# set_start_value(m2[:x], solvedx)
# set_start_value(m2[:y], solvedy)
# set_start_value.(m2[:P], solvedP)

with_SCS_3iters = with_optimizer(SCS.Optimizer, eps=1e-10, max_iters=3, warm_start=true)
optimize!(m2, with_SCS_3iters)
termination_status(m2)
```
```
----------------------------------------------------------------------------
	SCS v2.0.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2017
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 12, CG tol ~ 1/iter^(2.00)
eps = 1.00e-10, alpha = 1.50, max_iters = 3, normalize = 1, scale = 1.00
acceleration_lookback = 20, rho_x = 1.00e-03
Variables n = 6, constraints m = 9
Cones:	linear vars: 9
Setup time: 3.53e-05s
SCS using variable warm-starting
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0| 6.15e+00  1.28e+00  7.53e-01 -5.71e+01 -7.61e+00  0.00e+00  2.28e-05 
     3| 4.22e-01  2.59e-01  2.60e-01 -6.17e+00 -1.09e+01  4.17e-16  4.02e-05 
----------------------------------------------------------------------------
Status: Solved/Inaccurate
Hit max_iters, solution may be inaccurate
Timing: Solve time: 4.18e-05s
	Lin-sys: avg # CG iterations: 2.25, avg solve time: 1.28e-06s
	Cones: avg projection time: 1.44e-07s
	Acceleration: avg step time: 2.35e-06s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 5.9819e-16, dist(y, K*) = 0.0000e+00, s'y/|s||y| = 7.1798e-02
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 4.2229e-01
dual res:   |A'y + c|_2 / (1 + |c|_2) = 2.5927e-01
rel gap:    |c'x + b'y| / (1 + |c'x| + |b'y|) = 2.6037e-01
----------------------------------------------------------------------------
c'x = -6.1744, -b'y = -10.8735
============================================================================

ALMOST_OPTIMAL::TerminationStatusCode = 7
```

**Comment by blegat** [comment]
Isn't the difference between `m2` and `m3` the fact that in `m3` you also set the start for slack and dual while in `m2` you only set the start for primal ?

**Comment by kalmarek** [comment]
SCS will ignore primal when dual and slack are not set:
https://github.com/JuliaOpt/SCS.jl/blob/master/src/c_wrapper.jl#L65
and this is what I believe happening, based on Your comment.

So maybe the question should be: is it possible to set dual and slack from the level of MOI?

**Comment by blegat** [comment]
Yes, see http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.ConstraintPrimalStart and http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.ConstraintDualStart

**Comment by kalmarek** [comment]
sorry for dumb questions, but the documentation is rather sparse at the moment:

I tried copying solution from `m` to `m2`:
```julia
with_SCS = with_optimizer(SCS.Optimizer,
    eps=1e-10,
#     max_iters=3,
    warm_start=true,
    verbose=false)

with_SCS_3iters = with_optimizer(SCS.Optimizer,
    eps=1e-10,
    max_iters=3,
    warm_start=true,
    verbose=true)

m = example_problem(Model(with_SCS))

optimize!(m)

m2 = example_problem(Model(with_SCS_3iters));
MOI.set(m2, MOI.VariablePrimalStart(), m2[:x], value(m[:x]))
MOI.set(m2, MOI.VariablePrimalStart(), m2[:y], value(m[:y]))
MOI.set.(m2, MOI.VariablePrimalStart(), m2[:P], value.(m[:P]))

# is this how you iterate over constraints?
for (F,S) in MOI.get(m.moi_backend, MOI.ListOfConstraints())
    cnstrs = MOI.get(m.moi_backend, MOI.ListOfConstraintIndices{F,S}())
    for c in cnstrs
        dual_val = MOI.get(m.moi_backend, MOI.ConstraintDual(), c)
        slack_val = MOI.get(m.moi_backend, MOI.ConstraintPrimal(), c)
        MOI.set(m2.moi_backend, MOI.ConstraintDualStart(), c, dual_val)
        MOI.set(m2.moi_backend, MOI.ConstraintPrimalStart(), c, slack_val)
    end
end

optimize!(m2)
```
however I still get warnings:
```
┌ Warning: MathOptInterface.ConstraintPrimalStart() is not supported by MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{SCS.Optimizer,MathOptInterface.Utilities.UniversalFallback{JuMP._MOIModel{Float64}}},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Bridges.AllBridgedConstraints{Float64}}}. This 
│   information will be discarded. = information will be discarded.
└ @ MathOptInterface.Utilities /home/kalmar/.julia/packages/MathOptInterface/QVlW6/src/Utilities/copy.jl:133
┌ Warning: MathOptInterface.ConstraintDualStart() is not supported by MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{SCS.Optimizer,MathOptInterface.Utilities.UniversalFallback{JuMP._MOIModel{Float64}}},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Bridges.AllBridgedConstraints{Float64}}}. This 
│   information will be discarded. = information will be discarded.
└ @ MathOptInterface.Utilities /home/kalmar/.julia/packages/MathOptInterface/QVlW6/src/Utilities/copy.jl:133
...
```

**Comment by blegat** [comment]
Only `VariablePrimalStart` is implemented for the MOI SCS wrapper.

**Comment by kalmarek** [comment]
as noted above implementing only `VariablePrimalStart` is pointless for SCS; what needs to be done for `ConstraintDualStart` and `ConstraintPrimalStart`?

(I see that `load` functions are already defined, with typos though)

**Comment by blegat** [comment]
> (I see that `load` functions are already defined, with typos though)

Indeed, it seems we only need to add `supports` methods
https://github.com/JuliaOpt/SCS.jl/blob/980ef0f1032eb45be43e8a3d7a701f87257f9434/src/MOI_wrapper.jl#L82

**Comment by kalmarek** [comment]
You're missing comma after Union;

unfortunately I've already tried this and I get the same warnings (and results). note:
```julia
F = MOI.SingleVariable
S = MOI.EqualTo{Float64}

MOI.supports(Model(with_SCS).moi_backend, MOI.ConstraintDualStart(), MOI.ConstraintIndex{F,S})
```
still returns `false`;

the defined `support`s functions are for
`MOI.supports(Model(with_SCS).moi_backend.optimizer.model.optimizer, MOI.ConstraintDualStart(), MOI.ConstraintIndex{F,S}))` and the chain gets broken somewhere

**Comment by blegat** [comment]
Good point, we need to implement starting values for bridges

**Comment by blegat** [comment]
Let's first check if it works if all the constraints are natively supported, i.e.
https://github.com/JuliaOpt/SCS.jl/blob/980ef0f1032eb45be43e8a3d7a701f87257f9434/src/MOI_wrapper.jl#L8-L9
then we will add support for bridges in MOI.

**Comment by kalmarek** [comment]
@blegat what do you mean by natively supported?

reading https://github.com/JuliaOpt/MathOptInterface.jl/issues/528 I understand that we need to wait to remove VectorOfVariables support (as this will be transformed by `Bridge`) is that correct?

**Comment by blegat** [comment]
Indeed, I was ambiguous, I meant natively supported by the MOI wrapper (i.e. no bridge are needed). So it should work if for a model like
```julia
model = Model(with_optimizer(SCS.Optimizer))
@variable(model, x[1:2])
@constraint(model, [x[1] - x[2]] in MOI.Nonnegatives(1))
@constraint(model, x .+ 1 in MOI.SecondOrderCone(2))
@objective(model, Max, sum(x))
```

**Comment by blegat** [comment]
I have opened an issue for start values in the bridges: https://github.com/JuliaOpt/MathOptInterface.jl/issues/684

**Pull request merged**
