### PR TITLE
Multi-gcc binaryBuilder update

### PR DESCRIPTION
**Pull request by juan-pablo-vielma**
Updates to the multi gcc-version of binarybuilder, but does not add the symlink magic for BLAS libraries as this adds additional complexity that does not seem to be necessary (does not fix the known issues with ArchLinux).

### CODE REVIEW

**Comment by kalmarek** [comment]
I have a very mimimal patch for SCS.jl to enable `scs-2.1.1`, but currenty

* #144 drops julia-0.6,
* #147 adds gpu solver and modifies the SCSStructs(to be merged after #144).
* Then @juan-pablo-vielma will have to update this pull (it is still `scs-v2.0.2`).
* Finally we release SCSBuilder with `scs-v2.1.1` and
* I will provide update to for `SCS.jl` and `v0.6` can be officially released

@juan-pablo-vielma, @blegat do we agree on this plan?

**Comment by juan-pablo-vielma** [comment]
I suggest releasing this PR as `v0.5.2` (or `v0.6`) to have the last version with `scs-v2.0.2` that runs with an up to date version of BB (this should be a simple PR whose only visible change is dropping julia 0.6). Then add #147 and `scs-v2.1.1` as `v0.6` (or `v0.7`). Maybe even the last two should be different tags (`scs-v2.1.1` may require new tests for added features?)

**Comment by juan-pablo-vielma** [comment]
Ok, spoke too soon. Not sure why coverage dropped, but I imagine this PR needs #144 first.

**Comment by kalmarek** [comment]
coverage is very flaky: e.g. `types.jl` are still 100% covered, for sure.
If you don't like our planet, you can re-trigger the build, percentages will change ;-)

**Comment by juan-pablo-vielma** [comment]
still failing coverage. I released `v2.1.1` in `SCSBuilder`. Tried to test it, but it seems it needs updates to `SCS.jl` to work.

**Comment by blegat** [comment]
It's known that coverage drops when dropping Julia v0.6 because Julia v0.6 was too generous but Julia v1.0 is not generous enough: https://github.com/JuliaCI/Coverage.jl/issues/187
Adding Julia v1.1 an v1.2 might help

**Comment by juan-pablo-vielma** [comment]
Ok, v1.1 and v1.2 also passing, but there is still a drop in coverage

**Comment by blegat** [comment]
@juan-pablo-vielma Can you rebase ?

**Comment by juan-pablo-vielma** [comment]
Rebasing done.

**Comment by blegat** [comment]
LGTM, @kalmarek any objection to merge ?

**Comment by kalmarek** [comment]
@blegat not at all, I'm looking forward!

**Pull request merged**
